### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by nk932714** [oelna/fb-sleep-php#1]
Warning: usort() expects exactly 2 parameters, 3 given in /home/fb stats/index.php on line 218

**Comment by oelna** [comment]
sorry you had to wait so long for this, but I looked into the issue. no idea, why I messed up `usort` at the time of writing, but it should work ok now. while fixing things I also found Facebook had changed some of their code, so the matching had to be adjusted anyway. thanks for submitting the issue.

**Comment by nk932714** [comment]
Thanks @oelna
