### ISSUE TITLE
Facebook Freind or Any Facebook User?

### ISSUE THREAD

**Issue by karopass** [oelna/fb-sleep-php#2]
Hi!
I am interested in this awesome work! Can I know its work only for FB friends or any FB user?
If its working for only FB Friends, There any chance to extend it for any users?
Thanks a lot!

**Comment by oelna** [comment]
Sorry, no. The app gets the activity data from Facebook via the friends list, so you can only see your friends' activity at any given time. I don't believe there to be a way to extend the app to do this, as Facebook does not expose activity data publically for its users.
